# Loads default set of integrations. Do not remove.
default_config:

frontend:
  themes: !include_dir_merge_named themes

sensor: !include sensors/solaredge_modbus.yaml
template: !include_dir_merge_list templates/
automation: !include_dir_list automations/
script: !include_dir_list scripts/
scene: !include_dir_list scenes/

evohome: !include evohome.yaml
http: !include http.yaml

# Text to speech
tts:
  - platform: google_translate

# rest_command:
#   beeceptor:
#     url: "https://darrenm.free.beeceptor.com"
#     method: "post"
#     payload: '{"message": "{{ message }}", "value": "{{ states(input_number.target_temperature)}}"}'

homeassistant: !include customisations.yaml
