- platform: integration
  # Integrate the battery charging power flow to get energy
  name: energy_battery_charged
  source: sensor.power_battery_charging
  method: left
  unit_prefix: k
- platform: integration
  # Integrate the battery charging from solar power flow to get energy
  name: energy_battery_charged_solar
  source: sensor.power_battery_charging_solar
  method: left
  unit_prefix: k
- platform: integration
  # Integrate the battery discharging power flow to get energy
  name: energy_battery_discharged
  source: sensor.power_battery_discharging
  method: left
  unit_prefix: k
- platform: statistics
  name: EV Grid Export 10 Minute Average
  unique_id: ev_grid_export_10_minute_average
  entity_id: sensor.power_grid_export
  state_characteristic: mean
  sampling_size: 120
  max_age:
    minutes: 10
