- platform: integration
  # Integrate the battery charging power flow to get energy
  name: energy_battery_charged
  source: sensor.power_battery_charging
  method: left
  unit_prefix: k
- platform: integration
  # Integrate the battery charging from solar power flow to get energy
  name: energy_battery_charged_solar
  source: sensor.power_battery_charging_solar
  method: left
  unit_prefix: k
- platform: integration
  # Integrate the battery discharging power flow to get energy
  name: energy_battery_discharged
  source: sensor.power_battery_discharging
  method: left
  unit_prefix: k
- platform: statistics
  name: EV Solar Headroom 10 Minute Average
  unique_id: ev_solar_headroom_10_minute_average
  entity_id: sensor.ev_solar_headroom
  state_characteristic: mean
  sampling_size: 120
  max_age:
    minutes: 10
