- platform: integration
  # Integrate the battery charging power flow to get energy
  name: energy_battery_charged
  source: sensor.power_battery_charging
  method: left
  unit_prefix: k
- platform: integration
  # Integrate the battery charging from solar power flow to get energy
  name: energy_battery_charged_solar
  source: sensor.power_battery_charging_solar
  method: left
  unit_prefix: k
- platform: integration
  # Integrate the battery discharging power flow to get energy
  name: energy_battery_discharged
  source: sensor.power_battery_discharging
  method: left
  unit_prefix: k
