alias: Front door opened
description: "Sensor triggered whilst doors armed"
trigger:
  - type: opened
    platform: device
    device_id: 418011d6ab9e4a838444a882c031f000
    entity_id: 2e6c6b84a7975b03e72adc5133ec74e1
    domain: binary_sensor
condition:
  - condition: state
    entity_id: input_boolean.doors_armed
    state: "on"
    for:
      hours: 0
      minutes: 0
      seconds: 10
action:
  - action: notify.mobile_app_sm_s921b
    data:
      message: Front door opened
      title: Security alert
mode: single
